org.nrg.Feature=project_copying
org.nrg.Feature.project_copying.key=project_copying
org.nrg.Feature.project_copying.name=Project Copying
org.nrg.Feature.project_copying.OnByDefault=true
org.nrg.Feature.project_copying.description=Allows users to copy data from one project to another.